---

- name: file module
  hosts: all
  gather_facts: no

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/test
        state: directory

    - name: Copy file
      copy: 
        src: file/test.txt
        dest: /etc/test/test.txt
